apiVersion: v1
kind: Pod

metadata:
  name: configmap-demo

spec:
  containers:
  - name: nginx
    image: nginx

    env:
    - name: APP_NAME
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_NAME

    - name: ENV
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: ENV

    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: PORT